#spring应用名跟对外服务名
spring:
  profiles: module
#注册中心指向start
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    appname: ${spring.application.name}
    hostname: 127.0.0.1
    port: 8888
  client:
    service-url:
      defaultZone: http://admin_cjx:admin_cjx@${eureka.instance.hostname}:${eureka.instance.port}/eureka/