
server:
  port: 8001
 
spring:
  application:
    name: springcloud-common
 
#注册中心指向start    
eureka:
  instance:
    instance-id: springcloud-common
    appname: ${spring.application.name}
    hostname: localhost
  client: 
    service-url: 
      defaultZone: http://admin_cjx:admin_cjx@${eureka.instance.hostname}:8888/eureka/
#注册中心指向end