#spring应用名跟对外服务名
spring:
  profiles: redis-prd
  #redisConfig
  redis:
    host: 172.17.140.83
    port: 6379
    password: cjxwd86496048
    timeout: 30000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0