#应用实例
server:
  port: 8001

#spring应用名跟对外服务名
spring:
  profiles:
    include: common
  application:
    name: user
    servicename: SL_USER
  #redisConfig
  redis:
    host: 47.95.221.169
    port: 6379
    password: cjxadmin
    timeout: 30000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
  #druid jdbc池
  datasource:
    druid:
      username: root
      password: Cjxwd86496048
      url: jdbc:mysql://114.116.210.29:3306/info?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=CONVERT_TO_NULL
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#mybatis
mybatis:
  #如果Mapper接口跟xml放在一起,就不用指定xml的路径
  #mapper-locations: classpath:**/mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #数据操作语言的日志在控制台打印
#注册中心指向start
eureka:
  instance:
    instance-id: ${spring.application.name}
    appname: ${spring.application.name}
    hostname: 47.95.221.169
  client:
    service-url:
      defaultZone: http://admin_cjx:admin_cjx@${eureka.instance.hostname}:8888/eureka/