
server:
  port: 8001
 
spring:
  application:
    name: springcloud-common
 
#注册中心指向start    
eureka:
  instance:
    instance-id: springcloud-common
    appname: ${spring.application.name}
    hostname: 47.95.221.169
  client: 
    service-url: 
      defaultZone: http://admin_cjx:admin_cjx@${eureka.instance.hostname}:8888/eureka/
  server:
    # 关闭自我保护
    enable-self-preservation: false
    # 清理服务器
    eviction-interval-timer-in-ms: 60000