
server:
  port: 8001
 
spring:
  application:
    name: springcloud-common
 
#注册中心指向start    
eureka:
  instance:
    instance-id: springcloud-common
    appname: ${spring.application.name}
    hostname: 47.95.221.169
  client: 
    service-url: 
      defaultZone: http://admin_cjx:admin_cjx@${eureka.instance.hostname}:8888/eureka/
#注册中心指向end

#feign的配置，连接超时及读取超时配置
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
#feign的配置，连接超时及读取超时配置