#spring应用名跟对外服务名
spring:
  profiles: datasource-dev
  #druid jdbc池
  datasource:
      druid:
        username: root
        password: Cjxwd86496048
        url: jdbc:mysql://114.116.210.29:3306/info?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=CONVERT_TO_NULL
        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 600000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        useGlobalDataSourceStat: true
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#mybatis
mybatis:
  #如果Mapper接口跟xml放在一起,就不用指定xml的路径
  #mapper-locations: classpath:**/mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #数据操作语言的日志在控制台打印