#spring应用名跟对外服务名
spring:
  profiles: redis-dev
  #redisConfig
  redis:
    host: 47.95.221.169
    port: 6379
    password: cjxwd86496048
    timeout: 3000
    jedis:
      pool:
        max-active: 500
        max-wait: 6000
        max-idle: 1000
        min-idle: 4