#spring应用名跟对外服务名
spring:
  profiles: redis
  #redisConfig
  redis:
    host: 47.95.221.169
    port: 6379
    password: cjxadmin
    timeout: 30000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0