
server:
  port: 8001
 
spring:
  application:
    name: springcloud-common
    servicename: SL_COMMON
    #redisConfig
    redis:
      host: 47.95.221.169
      port: 6379
      password: cjxadmin
      jedis:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 500
          min-idle: 0
      lettuce:
        shutdown-timeout: 0
    #redisConfig
#注册中心指向start    
eureka:
  instance:
    instance-id: springcloud-common
    appname: ${spring.application.name}
    hostname: 47.95.221.169
  client: 
    service-url: 
      defaultZone: http://admin_cjx:admin_cjx@${eureka.instance.hostname}:8888/eureka/
#注册中心指向end